title: maentx
description: >- # this means to ignore newlines until "baseurl:"
  Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
    recipes:
        output: true
    tales:
        output: true

permalink: none

social-links:
  - name: twitter
    external-url: https://twitter.com/maentx

  - name: linkedin
    external-url: https://linkedin.com/in/marian-h%C3%A4ntsch-6987a3103/

  - name: github-user
    external-url: https://github.com/maentx
    icon-class: fab fa-2x fa-github

  - name: email
    external-url: 'mailto:maentx@outlook.com'
    icon-class: fas fa-2x fa-envelope-open

  - name: rss
    internal-url: feed.xml
    icon-class: fas fa-2x fa-rss

defaults:
  - scope:
      path: ""
      type: "recipes"
    values:
      layout: "recipe"
  - scope:
      path: ""
      type: "tales"
    values:
      layout: "tale"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
